// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeyvligdaajudlyhldeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleXZsaWdkYWFqdWRseWhsZGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MjI2MTgsImV4cCI6MjA1NDQ5ODYxOH0.yNWfzopufhFPT6GDfQFNhtC7Xv-e8d9ZMw-2qsduYzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);